### ISSUE TITLE
adding all keys listed in Ring spec

### ISSUE THREAD

**Issue by yogthos** [igrishaev/ring-jdk-adapter#1]
It looks like current implementation is missing some keys listed in the [spec](https://github.com/ring-clojure/ring/blob/master/SPEC.md). For example, [ring-headers](https://github.com/ring-clojure/ring-headers) middleware breaks because it gets a null pointer trying to parse the scheme in [request-url](https://github.com/ring-clojure/ring/blob/dde9716e23f85497df4ea0deba148fd22ac99c6c/ring-core/src/ring/util/request.clj#L5).

**Comment by igrishaev** [comment]
It looks like I'm missing the `scheme` key, let me take a look

**Comment by igrishaev** [comment]
Could you please try it with the latest release?

```
;; lein
[com.github.igrishaev/ring-jdk-adapter "0.1.1"]

;; deps
com.github.igrishaev/ring-jdk-adapter {:mvn/version "0.1.1"}
```

At the moment, the `scheme` field is always `:http` because the adapter doesn't support HTTPS server. I think I can implement it a bit later.

I added some tests that involve functions from `ring.util.request` namespace, fixed one more minor bug.

Can you please let me know if it works for you?

**Comment by yogthos** [comment]
Looks good on my end!
